# Generated by Django 4.2.11 on 2024-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=255, verbose_name='About us')),
                ('projects', models.CharField(max_length=255, verbose_name='Projects')),
                ('works', models.CharField(max_length=255, verbose_name='Works')),
                ('team', models.CharField(max_length=255, verbose_name='Team')),
                ('contacts', models.CharField(max_length=255, verbose_name='Contacts')),
                ('hero_subtitle', models.TextField(verbose_name='Hero-subtitle')),
                ('hero_btn', models.CharField(max_length=50, verbose_name='Hero_btn')),
                ('about_subtitle', models.CharField(max_length=100, verbose_name='About_subtitle')),
                ('about_p1', models.TextField(verbose_name='About_p1')),
                ('about_p2', models.TextField(verbose_name='About_p2')),
                ('about_p3', models.TextField(verbose_name='About_p3')),
            ],
        ),
    ]
